# Generated by Django 5.1.1 on 2024-09-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats_everywhere', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catdata',
            name='image',
            field=models.ImageField(upload_to='cats_everywhere/'),
        ),
    ]
