# Generated by Django 5.1.1 on 2024-09-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats_everywhere', '0003_alter_catdata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catdata',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
